# Copyright 2019 Luis Valledor / Laura Lamelas
# Last revision 01.2023
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


#' @name mcia_plot
#' @title Multiple coinertia plot
#' @description A function to plot different aspects of multiple coinertia analysis
#' @usage mcia_plot(mcia_list, treatment = 1, compX = 1,
#' compY = 2, compZ = NULL, plottype = "Composite", useannot = FALSE,
#' levelchoice = "all", fontsizes = c(14,10,16,12), fortopscoring = c(1,20,"abs"),
#' confidence = 0.9)
#' @param mcia_list List containing the multiple coinertia analysis, generated with pRocessomics::mcia_analysis function
#' @param treatment numeric value to determine the colors and symbols to be displayed in the plot, used in Score plot and Topscring plot. Available optiones are:
#' \itemize{
#' \item 1 to show different colors according to treatment 1 (treatment1col)
#' \item 2 to show different colors according to treatment 2 (treatment2col)
#' \item 3 to show different colors according to the combination of both treatments
#' \item 4 to show different colors according to treatment 1 and different symbols for treatment 2
#' }
#' @param compX component to be plotted in X axis in Score and Var plots, default 1
#' @param compY component to be plotted in X axis in Score and Var plots, default 2
#' @param compZ component to be plotted in Z axis for 3D plots in SynVar and Var plots, default NULL
#' @param plottype available options:
#' \itemize{
#' \item Scree, explained variance plot
#' \item SynVar, sample plot each dot represent a sample
#' \item SynVar_Ellipse, score plot with confidence ellipses by treatment
#' \item Topscoring, topscoring variables in the selected dimension
#' \item Var, variable plot, each dot represent a variable
#' \item Biplot, biplot showing samples and variables
#' \item CoIn, coinertia plot showing samples and omiclevels
#' \item Pseudoeigen, plot showing correlations among datasets
#' \item Composite: combination of the four most representative plots of the analysis
#' \item All all aforementioned plots will be exported as .pdf files in your working directory
#' }
#' @param levelchoice character vector; quoted name(s) of omiclevels (one or more) to plot, can be set to "all" for include every omiclevel
#' @param useannot logical, indicating whether an annotation file should be used. Please note that the annotation file can be only generated by pRocessomics::importannotation() function
#' @param fortopscoring vector (length = 3) indicating the number of the component to be analyzed, the top n loadings to plot and the mode to compute "abs" for absolute value and "posneg" for positive and negative loading analyzed separately
#' @param fontsizes vector containing the font sizes to use in the plots
#' @param confidence numeric value between 0 and 1 for confidence ellipses in SynVar_Ellipse plot

#' @return mcia plot
#' @author Luis Valledor and Laura Lamelas
#'
#' @export
#' @importFrom plotly layout plot_ly add_segments add_trace subplot style ggplotly
#' @importFrom ggplot2 ggplot theme scale_color_manual scale_fill_manual stat_ellipse geom_point theme_minimal aes
#' @importFrom stats na.omit


mcia_plot <-
  function(mcia_list,
           treatment = 1,
           compX = 1,
           compY = 2,
           compZ = NULL,
           plottype = "Composite",
           useannot = FALSE,
           levelchoice = "all",
           fontsizes = c(14, 10, 16, 12),
           fortopscoring = c(1, 20, "abs"),
           confidence = 0.9) {
    # Checks ----
    if (!inherits(mcia_list,"mciaanalysis"))
      stop("mciaanalysis object is expected, please run mcia_analysis first")
    if (!inherits(mcia_list[[1]], "mcia"))
      stop("mciaanalysis object expected, please run mcia_analysis first")
    if (plottype %in% c(
      "Composite",
      "SynVar",
      "SynVar_Ellipse",
      "Scree",
      "Var",
      "Topscoring",
      "CoIn",
      "Pseudoeigen",
      "All",
      "Biplot"
    ) == FALSE)
    stop("Please select a valid plot type")
    if (useannot == T && is.null(mcia_list$annotations)) {
      texts_wizard("Annotation matrix not provided. Considering useannot=F")
      texts_wizard("Please check/repeat mcia_analysis() including an annotation matrix")
      texts_wizard("Read help or follow the tutorial for more information.")
      useannot = FALSE
    }
   
    # Required objects ----
    mcia_object <- mcia_list$mcia
    treatmentstable <- mcia_list$treatments
    annotations <- mcia_list$annotations
    datasetnames <- mcia_list$datasetnames
    treatmentnames <- colnames(treatmentstable)
    originaldata <- mcia_list$originaldata
    # Custom aesthetics ----
    custom.aes <- Filter(function(x) "color.pRo" %in% class(get(x)), ls(envir= .GlobalEnv))
    if(length(custom.aes) != 0){
      for (i in 1:length(custom.aes)){
        new.aes <- get(custom.aes[i],envir=.GlobalEnv)
        
        switch(class(new.aes)[2], 
               "treatment" = paleta_tratamientos <- new.aes,
               "levels" = paleta_niveles <- new.aes, 
               "continuos" = paleta_continuo <- new.aes,
               "mapman" = paleta_mapman <- new.aes,
               "symbols" = simbolos <- new.aes, 
               "fontsizes" = fontsizes <- new.aes)
      }
      
    }
    
    
    ## Omiclevels in use ----
    
    nivelesomicos <-
      nrow(mcia_object$mcoa$lambda) #En teoria debemos pasarle los tratamientos...
    
    variablesxnivel <- as.vector(mcia_object$mcoa$blo) #Aquí sabemos cuantas variables tenemos por nivel
    niveles <- length(variablesxnivel) #lau: esto es lo mismo que niveles omicos
    
    if(any(levelchoice %in% rownames(mcia_object$mcoa$lambda)==F)&levelchoice !="all"){
      stop(paste("levelchoice argument invalid.\nHint: Valid levelchoice argument can only include: ", paste(rownames(mcia_object$mcoa$lambda), collapse = ", "), "or combinations of them (if more than one omic level is in use)",sep=""))
    }
    # Top Scoring plot -----
    if (plottype == "Topscoring") {
      if (useannot == T) {
        topsco_plot <-
          topscoring(
            mcia_list,
            originaldata = originaldata,
            treatmentstable = treatmentstable,
            n = fortopscoring[2],
            mode = fortopscoring[3],
            numberofcomponents = fortopscoring[1],
            treatment = treatment,
            annots = annotations
          )
      }
      if (useannot == F) {
        topsco_plot <-
          topscoring(
            mcia_list,
            originaldata = originaldata,
            treatmentstable = treatmentstable,
            n = fortopscoring[2],
            mode = fortopscoring[3],
            numberofcomponents = fortopscoring[1],
            treatment = treatment,
            annots = NULL
          )
      }
      return(topsco_plot)
    }
    
    # Syn Var Plot ----
    
    ncomp = ncol(mcia_object$mcoa$SynVar)
    if (plottype %in% c("SynVar","SynVar_Ellipse")) {
      if (compX > ncomp)
        stop(
          paste(
            "\nX-Axis component do not exist. Only ",
            ncol(mcia_object$mcoa$SynVar),
            " components were defined in MCIA analysis",
            sep = ""
          )
        )
      if (compY > ncomp)
        stop(
          paste(
            "\nY-Axis component do not exist. Only ",
            ncol(mcia_object$mcoa$SynVar),
            " components were defined in MCIA analysis",
            sep = ""
          )
        )
      if (treatment != 4) {
        if (treatment == 1)
          tratamientocolores <- as.vector(treatmentstable[, 1])
        if (treatment == 2)
          tratamientocolores <- as.vector(treatmentstable[, 2])
        if (treatment == 3)
          tratamientocolores <- as.vector(treatmentstable[, 3])
        
        tratamientocolores <-
          factor(tratamientocolores, levels = unique(tratamientocolores))
        
        if(plottype == "SynVar_Ellipse"){
          replicates <- nrow(treatmentstable)/length(unique(tratamientocolores))
          if (replicates < 4){plottype = "SynVar"}
          if (!is.null(compZ)){plottype = "SynVar"}
          
        }
        if(plottype == "SynVar_Ellipse"){
          colcolcol <- paleta_tratamientos[1:length(unique(tratamientocolores))]
          if (is.null(compZ)) {# Plot 2D, 1 factor.
            
            h <- ggplot2::ggplot(as.data.frame(mcia_object$mcoa$SynVar), 
                                 ggplot2::aes(mcia_object$mcoa$SynVar[, compX],
                                              mcia_object$mcoa$SynVar[, compY],
                                              color = factor(tratamientocolores,levels=unique(tratamientocolores)))) + 
              ggplot2::theme_minimal() + 
              ggplot2::stat_ellipse(level=confidence, 
                                    geom = "polygon", 
                                    alpha=0.3, 
                                    ggplot2::aes(fill=factor(tratamientocolores,levels=unique(tratamientocolores)))) + 
              ggplot2::geom_point()+    
              ggplot2::theme(legend.title = element_blank())
            
            j <- h + ggplot2::scale_color_manual(values = colcolcol) + 
              ggplot2::scale_fill_manual(values=colcolcol) 
            
            mcoa_score_plot3 <- plotly::ggplotly(j)
            
            mcoa_score_plot2 <- plotly::layout(
              mcoa_score_plot3,
              
              xaxis = list(
                zeroline=T,
                title = list(
                  text = paste(
                    "Component",
                    compX,
                    sep = " "
                  ),
                  font =list(
                    size = fontsizes[1]
                  )
                ),
                tickfont = list(size =
                                  fontsizes[2])
              ),
              yaxis = list(
                zeroline=T,
                title = list(
                  text = paste(
                    "Component",
                    compY,
                    "-",
                    sep = " "
                  ),
                  font =
                    list(size = fontsizes[1])
                ),
                tickfont = list(size =
                                  fontsizes[2])
              ),
              title = list(text = "MCIA Synthetic Scores Plot", font =
                             list(size = fontsizes[3])),
              legend = list(font = list(size =
                                          fontsizes[4]))
            )
            
            #retocamos trazas elipses
            mcoa_score_plot2_t <- mcoa_score_plot2
            ellips_text <- paste(confidence*100,"% confidence","<br>interval; ",unique(tratamientocolores))
            
            for(i in (1:length(unique(colcolcol)))){
              mcoa_score_plot2_t <- plotly::style(mcoa_score_plot2_t, 
                                                  hoverinfo = "text", text = ellips_text[i], traces = i,name = ellips_text[i], showlegend=T)
            }
            #retocamos trazas samples
            mcoa_score_plot_tp <- mcoa_score_plot2_t
            track <- c((1+length(unique(colcolcol))):(length(unique(colcolcol))*2)) 
            ptra <- as.data.frame(cbind(rownames(mcia_object$mcoa$SynVar),treatmentstable[,treatment]))
            a <- lapply(split(ptra, ptra[,2]), function(x) (x[,1]))
            v <- c()
            for(i in 1:length(a)){
              v[i] <- length(a[[i]])
            }
            if(var(v) != 0){
              lenmx <- max(v)
              d <- c()
              for(i in 1:length(a)){
                d[i] <- lenmx - length(a[[i]])
                a[[i]] <- c(a[[i]],rep(NA,d[i]))
              }
            }
            b <- do.call(cbind, a)
            
            for(i in (1:length(unique(colcolcol)))){
              mcoa_score_plot_tp <- plotly::style(mcoa_score_plot_tp, 
                                                  hoverinfo = "text",
                                                  text = paste("Sample: ",stats::na.omit(b[,i]), sep=""),
                                                  showlegend = TRUE, 
                                                  name = colnames(b)[i],
                                                  traces = track[i] )}
            return(mcoa_score_plot_tp)}
        }
        else {
          if(is.null(compZ)){# Plot 2D, 1 factor.
          mcoa_ScorePlot <- plotly::plot_ly(
            as.data.frame(mcia_object$mcoa$SynVar),
            x = ~ mcia_object$mcoa$SynVar[, compX],
            y = ~ mcia_object$mcoa$SynVar[, compY],
            hoverinfo = "text",
            text = paste("Sample:", rownames(mcia_object$mcoa$SynVar), sep = " "),
            showlegend = TRUE,
            type = "scatter",
            mode = "markers",
            color = tratamientocolores,
            colors = paleta_tratamientos[1:length(unique(tratamientocolores))],
            #symbol = factor(rep(c(1:nrow(mcia_object$mcoa$lambda)),each=nrow(mcia_object$mcoa$SynVar)), levels=datasetnames),
            #symbols = simbolos[1:length(unique(tratamientocolores))],
            marker = list(size = 11)
          )
          mcoa_ScorePlot <-
            plotly::layout(
              mcoa_ScorePlot,
              
              xaxis = list(
                title = list(
                  text = (paste("Component", compX, sep = " ")),
                  font = list(size = fontsizes[1])
                ),
                tickfont = list(size = fontsizes[2])
              ),
              
              yaxis = list(
                title = list(
                  text = (paste("Component", compY, sep = " ")),
                  font = list(size = fontsizes[1])
                ),
                tickfont = list(size = fontsizes[2])
              ),
              
              title = list(text = "MCIA Synthetic Scores Plot",
                           font = list(size = fontsizes[3])),
              legend = list(font = list(size = fontsizes[4]))
            )
          
          return(mcoa_ScorePlot)
        }
        
        if (!is.null(compZ)) {
          if (compZ > ncomp)
            stop(
              paste(
                "\nZ-Axis component do not exist. Only ",
                ncol(mcia_object$mcoa$SynVar),
                " components were defined in MCIA analysis",
                sep = ""
              )
            )
          
          mcoa_ScorePlot <-
            plotly::plot_ly(
              as.data.frame(mcia_object$mcoa$SynVar),
              x = ~ mcia_object$mcoa$SynVar[, compX],
              y = ~ mcia_object$mcoa$SynVar[, compY],
              z = ~ mcia_object$mcoa$SynVar[, compZ],
              hoverinfo = "text",
              text = paste("Sample:", rownames(mcia_object$mcoa$SynVar), sep =
                             " "),
              showlegend = TRUE,
              type = "scatter3d",
              mode = "markers",
              color = tratamientocolores,
              colors = paleta_tratamientos[1:length(unique(tratamientocolores))],
              #symbol = factor(rep(c(1:nrow(mcia_object$mcoa$lambda)),each=nrow(mcia_object$mcoa$SynVar)), levels=datasetnames),
              #symbols = simbolos[1:length(unique(tratamientocolores))],
              marker = list(size = 11)
            )
          
          mcoa_ScorePlot <-
            plotly::layout(
              mcoa_ScorePlot,
              scene = list(
                xaxis = list(
                  title = list(
                    text = paste("Component", compX, sep = " "),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                yaxis = list(
                  title = list(
                    text = paste("Component", compY, sep = " "),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                zaxis = list(
                  title = list(
                    text = paste("Component", compZ, sep = " "),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                )
              ),
              title = list(text = "MCIA Synthetic Scores Plot",
                           font = list(size = fontsizes[3])),
              legend = list(font = list(size = fontsizes[4]))
            )
          
          return(mcoa_ScorePlot)
        }
        }
      }
      if (treatment == 4) {
        if (is.null(compZ)) {
          mcoa_ScorePlot <-
            plotly::plot_ly(
              as.data.frame(mcia_object$mcoa$SynVar),
              x = ~ mcia_object$mcoa$SynVar[, compX],
              y = ~ mcia_object$mcoa$SynVar[, compY],
              hoverinfo = "text",
              text = paste("Sample:", rownames(mcia_object$mcoa$SynVar), sep =
                             " "),
              showlegend = TRUE,
              type = "scatter",
              mode = "markers",
              color = factor(treatmentstable[, 1], levels = unique(treatmentstable[, 1])),
              colors = paleta_tratamientos[1:length(unique(treatmentstable[, 1]))],
              symbol = factor(treatmentstable[, 2], levels =
                                unique(treatmentstable[, 2])),
              symbols = simbolos[1:length(unique(treatmentstable[, 2]))],
              marker = list(size = 11)
            )
          mcoa_ScorePlot <-
            plotly::layout(
              mcoa_ScorePlot,
              
              xaxis = list(
                title = list(
                  text = paste("Component", compX, sep = " "),
                  font = list(size = fontsizes[1])
                ),
                tickfont = list(size = fontsizes[2])
              ),
              
              yaxis = list(
                title = list(
                  text = paste("Component", compY, sep = " "),
                  font = list(size = fontsizes[1])
                ),
                tickfont = list(size = fontsizes[2])
              ),
              
              title = list(text = "MCIA Synthetic Scores Plot",
                           font = list(size = fontsizes[3])),
              legend = list(font = list(size = fontsizes[4]))
            )
          
          return(mcoa_ScorePlot)
        }
        
        if (!is.null(compZ)) {
          if (compZ > ncol(mcia_object$mcoa$SynVar))
            stop(
              paste(
                "\nZ-Axis component do not exist. Only ",
                ncol(mcia_object$mcoa$SynVar),
                " components were defined in MCIA analysis",
                sep = ""
              )
            )
          
          mcoa_ScorePlot <-
            plotly::plot_ly(
              as.data.frame(mcia_object$mcoa$SynVar),
              x = ~ mcia_object$mcoa$SynVar[, compX],
              y = ~ mcia_object$mcoa$SynVar[, compY],
              z = ~ mcia_object$mcoa$SynVar[, compZ],
              hoverinfo = "text",
              text = paste("Sample:", rownames(mcia_object$mcoa$SynVar), sep =
                             " "),
              showlegend = TRUE,
              type = "scatter3d",
              mode = "markers",
              color = factor(treatmentstable[, 1], levels = unique(treatmentstable[, 1])),
              colors = paleta_tratamientos[1:length(unique(treatmentstable[, 1]))],
              symbol = factor(treatmentstable[, 2], levels =
                                unique(treatmentstable[, 2])),
              symbols = simbolos[1:length(unique(treatmentstable[, 2]))],
              marker = list(size = 11)
            )
          mcoa_ScorePlot <-
            plotly::layout(
              mcoa_ScorePlot,
              scene = list(
                xaxis = list(
                  title = list(
                    text = (paste("Component", compX, sep = " ")),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                
                yaxis = list(
                  title = list(
                    text = (paste("Component", compY, sep = " ")),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                
                zaxis = list(
                  title = list(
                    text = (paste("Component", compZ, sep = " ")),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                )
              ),
              
              title = list(text = "MCIA Synthetic Scores Plot",
                           font = list(size = fontsizes[3])),
              legend = list(font = list(size = fontsizes[4]))
            )
          
          return(mcoa_ScorePlot)
        }
      }
    }
    
    # CoInertia Plot ----
    if (plottype == "CoIn") {
      #FLAG
      ## A partir de los scores sinteticos (la combinacion de los scores para los distintos niveles) vamos a definir unos segmentos
      ## (x1,y1),(x2,y2) para dibujar las conexiones de los distintos niveles omicos de cada muestra. Hay un valor fijo, el central,
      ## que es este SynVar, y luego tendremos tantos extremos como niveles omicos haya en su respectiva coordenada.
      if (treatment == 4) stop("CoIn plot do not accept two factors")   
      tratamientocolores <- treatmentstable[,treatment] 
      tratamientocolores <- factor(tratamientocolores, levels = unique(tratamientocolores))
   
      #FLAG
      segmentos <-
        cbind(mcia_object$mcoa$SynVar[, compX], mcia_object$mcoa$SynVar[, compY]) # Punto central X,Y para la combinacion de los componentes elegidos:
      segmentos_rep <- segmentos
      # Ahora la idea es crear una tabla de coordenadas en las que el valor centralha de repetirse tantas veces como niveles omicos tengamos:
      for (i in 2:nivelesomicos){
        segmentos_rep <- rbind(segmentos_rep, segmentos)}
      # Añadimos las columnas con los scores de los distintos niveles ómicos. El orden se mantiene:
      segmentos_rep <-
        cbind(segmentos_rep,
              mcia_object$mcoa$Tl1[, compX],
              mcia_object$mcoa$Tl1[, compY])
      
      # Usaremos los elementos anteriores para dibujar el Scatter plot
      mcoa_ScorePlot <-
        plotly::plot_ly(
          as.data.frame(mcia_object$mcoa$Tl1),
          x = ~ mcia_object$mcoa$Tl1[, compX],
          y = ~ mcia_object$mcoa$Tl1[, compY],
          type = "scatter",
          #hoverinfo = "text",  #Si la descomento para quitar coordenadas, las dos lineas de texto salen superpuestas. Se arregla quitando el /br y haciendo una linea larga, pero queda mas feo
          text = paste(
            "Sample:",
            do.call(rbind, lapply(strsplit(rownames(mcia_object$mcoa$Tl1), "\\."), function(x)
              x[[1]])),
            "</br> OmicLevel: ",
            rep(names(mcia_object$mcoa$blo), each = nrow(mcia_object$mcoa$SynVar))
          ),
          mode = "markers",
          showlegend = TRUE,
          color = rep(tratamientocolores, nivelesomicos),
          colors = paleta_tratamientos[1:length(unique(tratamientocolores))],
          symbol = factor(rep(
            names(mcia_object$mcoa$blo), each = nrow(mcia_object$mcoa$SynVar)
          ), levels = datasetnames),
          symbols = simbolos[1:length(unique(tratamientocolores))],
          marker = list(size = 11)
        )
      mcoa_ScorePlot <- plotly::add_segments(
        mcoa_ScorePlot,
        x = ~ segmentos_rep[, 1],
        xend = ~ segmentos_rep[, 3],
        y = ~ segmentos_rep[, 2],
        yend = ~ segmentos_rep[, 4],
        name = NULL,
        #mode = "line",
        inherit = F,
        ## as? no hereda las movidas del anterior
        type = "lines",
        ## esta l?nea es la clave en verdad, el resto adorna.
        hoverinfo = "none",
        alpha = 0.75,
        size = I(1),
        showlegend = FALSE,
        color = rep(tratamientocolores, nivelesomicos),
        #Luis: Añadi esto para colorear las lineas
        line = list(dash = "1px",  width = 2),
        #FLAG
        ## TODO cambiar el color para que vaya en funci?n del nivel
        opacity = 1
      )
      mcoa_ScorePlot <-
        plotly::layout(
          mcoa_ScorePlot,
          
          xaxis = list(
            title = list(
              text = (paste("Component", compX, sep = " ")),
              font = list(size = fontsizes[1])
            ),
            tickfont = list(size = fontsizes[2])
          ),
          
          yaxis = list(
            title = list(
              text = paste("Component", compY, sep = " "),
              font = list(size = fontsizes[1])
            ),
            tickfont = list(size = fontsizes[2])
          ),
          
          title = list(text = "MCIA Co-Inertia Normed Scores Plot",
                       font = list(size = fontsizes[3])),
          legend = list(font = list(size = fontsizes[4]))
        )
      return(mcoa_ScorePlot)
    }
    # Scree Plot ----
    if (plottype == "Scree") {
      #FLAG ***** Leyenda en ejes o en serires o ambas???? *********
      norm_eigenvalues <-
        mcia_object$mcoa$pseudoeig / sum(mcia_object$mcoa$pseudoeig) #Sacamos los autovalores, y os dividimos por la suma para tener el porcentaje de varianza en teoria recogida por cada tratamiento
      screeplotdata <-
        data.frame(
          Cs = paste("Comp", c(1:length(
            norm_eigenvalues
          )), sep = " "),
          ExplVar = norm_eigenvalues,
          Cumulat = cumsum(norm_eigenvalues) * 100 / sum(norm_eigenvalues),
          stringsAsFactors = FALSE
        )
      screeplotdata$Cs <-
        factor(screeplotdata$Cs, levels = unique(screeplotdata$Cs)[order(screeplotdata$ExplVar, decreasing = TRUE)]) # Ordenamos los PCs segun valor
      
      mcoa_ScorePlot <- plotly::plot_ly(screeplotdata)
      mcoa_ScorePlot <-
        plotly::add_trace(
          mcoa_ScorePlot,
          x =  ~ Cs,
          y =  ~ ExplVar,
          type = "bar",
          name = "Eigenvalues",
          marker = list(color = '#C9EFF9')
        )
      mcoa_ScorePlot <-
        plotly::add_trace(
          mcoa_ScorePlot,
          x =  ~ Cs,
          y =  ~ Cumulat,
          type = "scatter",
          mode = "lines+markers",
          yaxis = "y2",
          name = "Cumulative Eigenvalue",
          line = list(color = '#45171D')
        )
      mcoa_ScorePlot <-
        plotly::layout(
          mcoa_ScorePlot,
          title = list(text = "MCOA Screeplot",
                       font = list(size = fontsizes[3])),
          
          xaxis = list(
            title = "",
            titlefont = list(size = fontsizes[1]),
            tickfont = list(size = fontsizes[2])
          ),
          
          yaxis = list(
            side = 'left',
            title = list(text = "Eigenvalue",
                         font = list(size = fontsizes[1])),
            showgrid = F,
            zeroline = TRUE,
            tickfont = list(size = fontsizes[2])
          ),
          
          yaxis2 = list(
            side = 'right',
            overlaying = "y",
            title = list(text = "Cumulative (Percent)",
                         font = list(size = fontsizes[1])),
            showgrid = FALSE,
            zeroline = FALSE,
            tickfont = list(size = fontsizes[2])
          ),
          
          legend = list(x = 0.7, y = 0.1),
          legend = list(font = list(size = fontsizes[4]))
        )
      
      return(mcoa_ScorePlot)
    }
    # Var PLot ----
    if (plottype == "Var") {
      if (levelchoice == "all") { #este all se tendria que referir a all del analisis no de originaldata 
        if (useannot == FALSE) {
          
          mcoa_ScorePlot <-
            plotly::plot_ly(
              as.data.frame(mcia_object$mcoa$Tco),
              x = ~ mcia_object$mcoa$Tco[, compX],
              y = ~ mcia_object$mcoa$Tco[, compY],
              text = paste(
                "ID:",
                rownames(mcia_object$mcoa$Tco)
              ),
              type = "scatter",
              mode = "markers",
              marker = list(size = 6, opacity = 1),
              color = factor(rep(
                names(mcia_object$mcoa$blo), variablesxnivel
              ), levels = datasetnames),
              colors = paleta_niveles[1:length(datasetnames)]
            )
          
          mcoa_ScorePlot <-
            plotly::layout(
              mcoa_ScorePlot,
              title = list(text = "MCOA Variable Plot, all levels",
                           font = list(size = fontsizes[3])),
              xaxis = list(
                title = paste("Comp", compX, sep = " "),
                titlefont = list(size = fontsizes[1]),
                tickfont = list(size = fontsizes[2])
              ),
              yaxis = list(
                title = paste("Comp", compY, sep = " "),
                titlefont = list(size = fontsizes[1]),
                tickfont = list(size = fontsizes[2])
              ),
              legend = list(font = list(size = fontsizes[4]))
            )
          return(mcoa_ScorePlot)
        }
        if (useannot == TRUE) {
          #FLAG
          mapmanlevels <-
            as.numeric(unique(annotations[order(as.numeric(annotations[, 3])), 3]))
          mapmannames <-
            unique(annotations[order(as.numeric(annotations[, 3])), 4])
          mcoa_ScorePlot <-
            plotly::plot_ly(
              as.data.frame(mcia_object$mcoa$Tco),
              x = ~ mcia_object$mcoa$Tco[, compX],
              y = ~ mcia_object$mcoa$Tco[, compY],
              text = paste(
                "ID:",
                rownames(mcia_object$mcoa$Tco),
                "</br> Description: ",
                annotations[, 2],
                "</br> Mercator Bin: ",
                annotations[, 4]
              ),
              type = "scatter",
              mode = "markers",
              marker = list(size = 6, opacity = 1),
              color = factor(annotations[, 4], levels =
                               mapmannames),
              colors = paleta_mapman[mapmanlevels],
              symbol = factor(rep(
                names(mcia_object$mcoa$blo), variablesxnivel
              ), levels = datasetnames),
              symbols = simbolos[1:length(datasetnames)]
            )
          
          mcoa_ScorePlot <-
            plotly::layout(
              mcoa_ScorePlot,
              title = list(text = "MCOA Variable Plot, all levels",
                           font = list(size = fontsizes[3])),
              
              xaxis = list(
                title = list(
                  text = paste("Comp", compX, sep = " "),
                  font = list(size = fontsizes[1])
                ),
                tickfont = list(size = fontsizes[2])
              ),
              
              yaxis = list(
                title = list(
                  text = (paste("Comp", compY, sep = " ")),
                  font = list(size = fontsizes[1])
                ),
                tickfont = list(size = fontsizes[2])
              ),
              
              legend = list(font = list(size = fontsizes[4]))
            )
          return(mcoa_ScorePlot)
        }
      }
      if (levelchoice != "all") {
        
         
        aux.index.all <- factor(rep(
          names(mcia_object$mcoa$blo), variablesxnivel), levels = datasetnames) 
        aux.index.choices <- which(aux.index.all %in% levelchoice)
        
        if (useannot == FALSE) {
          mcoa_ScorePlot <-
            plotly::plot_ly(
              as.data.frame(mcia_object$mcoa$Tco),
              x = ~ mcia_object$mcoa$Tco[aux.index.choices, compX],
              y = ~ mcia_object$mcoa$Tco[aux.index.choices, compY],
              text = paste(
                "ID:",
                rownames(mcia_object$mcoa$Tco)[aux.index.choices]
              ),
              type = "scatter",
              mode = "markers",
              marker = list(size = 6, opacity = 1),
              colors = paleta_niveles[1:length(datasetnames)],
              color  = factor(rep(levelchoice,variablesxnivel[factor(levelchoice,levels = datasetnames)]), levels = datasetnames)
            )
          
          mcoa_ScorePlot <-
            plotly::layout(
              mcoa_ScorePlot,
              title = list(
                text = (
                  paste("MCOA Variable Plot, ", paste(levelchoice, collapse = ", "), " dataset", sep = "")
                ),
                font = list(size = fontsizes[3])
              ),
              
              xaxis = list(
                title = list(
                  text = (paste("Comp", compX, sep = " ")),
                  font = list(size = fontsizes[1])
                ),
                tickfont = list(size = fontsizes[2])
              ),
              
              yaxis = list(
                title = list(
                  text = (paste("Comp", compY, sep = " ")),
                  font = list(size = fontsizes[1])
                ),
                tickfont = list(size = fontsizes[2])
              ),
              
              legend = list(font = list(size = fontsizes[4]))
            )
          return(mcoa_ScorePlot)
        }
        if (useannot == TRUE) {
          mapmanlevels <-
            as.numeric(unique(annotations[order(as.numeric(annotations[aux.index.choices, 3])), 3]))
          mapmannames <-
            unique(annotations[order(as.numeric(annotations[aux.index.choices, 3])), 4])
          mcoa_ScorePlot <-
            plotly::plot_ly(
              as.data.frame(mcia_object$mcoa$Tco),
              x = ~ mcia_object$mcoa$Tco[aux.index.choices, compX],
              y = ~ mcia_object$mcoa$Tco[aux.index.choices, compY],
              text = paste(
                "ID:",
                rownames(mcia_object$mcoa$Tco)[aux.index.choices],
                "</br> Description: ",
                annotations[, 2][aux.index.choices],
                "</br> Mercator Bin: ",
                annotations[, 4][aux.index.choices]
              ),
              type = "scatter",
              mode = "markers",
              marker = list(size = 6, opacity = 1),
              color = factor(annotations[aux.index.choices, 4], levels =
                               mapmannames),
              colors = paleta_mapman[mapmanlevels],
              symbol = factor(rep(levelchoice,variablesxnivel[factor(levelchoice,levels = datasetnames)]), levels = datasetnames),
              symbols = simbolos[1:length(datasetnames)]
            )
          
          mcoa_ScorePlot <-
            plotly::layout(
              mcoa_ScorePlot,
              title = list(
                text = paste("MCOA Variable Plot, ", levelchoice, " dataset", sep = ""),
                font = list(size = fontsizes[3])
              ),
              
              xaxis = list(
                title = list(
                  text = paste("Comp", compX, sep = " "),
                  font = list(size = fontsizes[1])
                ),
                tickfont = list(size = fontsizes[2])
              ),
              
              yaxis = list(
                title = list(
                  text = (paste("Comp", compY, sep = " ")),
                  font = list(size = fontsizes[1])
                ),
                tickfont = list(size = fontsizes[2])
              ),
              
              legend = list(font = list(size = fontsizes[4]))
            )
          return(mcoa_ScorePlot)
        }
        
      }
    }
    
    # Biplot ----
    if (plottype == "Biplot") {
      if (treatment != 4) {
        if (treatment == 1)
          tratamientocolores <- treatmentstable[, 1]
        if (treatment == 2)
          tratamientocolores <- treatmentstable[, 2]
        if (treatment == 3)
          tratamientocolores <- treatmentstable[, 3]
        
        tratamientocolores <-
          factor(tratamientocolores, levels = unique(tratamientocolores))
        
        if (levelchoice == "all") {
          if (useannot == FALSE) {
            paletaintegrada <-
              c("#466fc7", paleta_tratamientos[1:length(unique(tratamientocolores))])
            mcoa_ScorePlot <- plotly::plot_ly()
            mcoa_ScorePlot <-
              plotly::add_trace(
                mcoa_ScorePlot,
                as.data.frame(mcia_object$mcoa$Tco),
                x = ~ mcia_object$mcoa$Tco[, compX],
                y = ~ mcia_object$mcoa$Tco[, compY],
                text = paste(
                  "ID:",
                  rownames(mcia_object$mcoa$Tco)
                ),
                type = "scatter",
                mode = "markers",
                marker = list(size = 5, opacity = 1),
                color = as.factor("Loadings"),
                colors = paletaintegrada,
                symbol = factor(rep(
                  names(mcia_object$mcoa$blo), variablesxnivel
                ), levels = datasetnames),
                symbols = simbolos[1:length(datasetnames)]
              )
            mcoa_ScorePlot <-
              plotly::add_trace(
                mcoa_ScorePlot,
                as.data.frame(mcia_object$mcoa$SynVar),
                x = ~ mcia_object$mcoa$SynVar[, compX],
                y = ~ mcia_object$mcoa$SynVar[, compY],
                text = paste(
                  "Sample:",
                  rownames(mcia_object$mcoa$SynVar),
                  sep = " "
                ),
                showlegend = TRUE,
                type = "scatter",
                mode = "markers",
                color = tratamientocolores,
                colors = paletaintegrada[2:length(paletaintegrada)],
                marker = list(size = 11),
                yaxis = "y",
                xaxis = "x"
              )
            
            mcoa_ScorePlot <-
              plotly::layout(
                mcoa_ScorePlot,
                
                xaxis = list(
                  title = list(
                    text = (paste("Component", compX, sep = " ")),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                
                yaxis = list(
                  title = list(
                    text = (paste("Component", compY, sep = " ")),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                
                title = list(text = "MCIA Biplot",
                             font = list(size = fontsizes[3])),
                legend = list(font = list(size = fontsizes[4]))
              )
            
            return(mcoa_ScorePlot)
          }
          if (useannot == TRUE) {
            #FLAG
            mapmanlevels <-
              as.numeric(unique(annotations[order(as.numeric(annotations[, 3])), 3]))
            mapmannames <-
              annotations[order(as.numeric(annotations[, 3])),]
            mapmannames <- as.vector(unique(mapmannames[, 4]))
            paletaintegrada <-
              c(paleta_mapman[mapmanlevels], paleta_tratamientos[1:length(unique(tratamientocolores))])
            
            
            mcoa_ScorePlot <- plotly::plot_ly()
            
            mcoa_ScorePlot <-
              plotly::add_trace(
                mcoa_ScorePlot,
                as.data.frame(mcia_object$mcoa$Tco),
                x = ~ mcia_object$mcoa$Tco[, compX],
                y = ~ mcia_object$mcoa$Tco[, compY],
                text = paste(
                  "ID:",
                  rownames(mcia_object$mcoa$Tco),
                  "</br> Description: ",
                  annotations[, 2],
                  "</br> Mercator Bin: ",
                  annotations[, 4]
                ),
                type = "scatter",
                mode = "markers",
                marker = list(size = 6, opacity = 1),
                color = factor(annotations[, 4], levels = unique(mapmannames)),
                colors = paletaintegrada,
                #FLAG
                symbol = factor(rep(
                  names(mcia_object$mcoa$blo), variablesxnivel
                ), levels = datasetnames),
                symbols = simbolos[1:length(datasetnames)]
              )
            
            mcoa_ScorePlot <-
              plotly::add_trace(
                mcoa_ScorePlot,
                as.data.frame(mcia_object$mcoa$SynVar),
                x = ~ mcia_object$mcoa$SynVar[, compX],
                y = ~ mcia_object$mcoa$SynVar[, compY],
                # hoverinfo ="text",
                text = paste(
                  "Sample:",
                  rownames(mcia_object$mcoa$SynVar),
                  sep = " "
                ),
                showlegend = TRUE,
                type = "scatter",
                mode = "markers",
                color = tratamientocolores,
                colors = paleta_tratamientos[1:length(unique(tratamientocolores))],
                marker = list(size = 11),
                yaxis = "y",
                xaxis = "x"
              )
            mcoa_ScorePlot <-
              plotly::layout(
                mcoa_ScorePlot,
                
                xaxis = list(
                  title = list(
                    text = paste("Component", compX, sep = " "),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                
                yaxis = list(
                  title = list(
                    text = paste("Component", compY, sep = " "),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                
                title = list(text = "MCIA Biplot",
                             font = list(size = fontsizes[3])),
                legend = list(font = list(size = fontsizes[4]))
              )
            return(mcoa_ScorePlot)
          }
        }
        
        if (levelchoice != "all") {
          
          aux.index.all <- factor(rep(
            names(mcia_object$mcoa$blo), variablesxnivel), levels = datasetnames) 
          aux.index.choices <- which(aux.index.all %in% levelchoice)
          
          if (useannot == FALSE) {
            
            paletaintegrada <- c("#466fc7", paleta_tratamientos[1:length(unique(tratamientocolores))])
            #paletaintegrada <- factor(paletaintegrada, levels = unique(paletaintegrada))
            mcoa_ScorePlot <- plotly::plot_ly()
            mcoa_ScorePlot <-
              plotly::add_trace(
                mcoa_ScorePlot,
                as.data.frame(mcia_object$mcoa$Tco),
                x = ~ mcia_object$mcoa$Tco[aux.index.choices, compX],
                y = ~ mcia_object$mcoa$Tco[aux.index.choices, compY],
                text = paste(
                  "ID:",
                  rownames(mcia_object$mcoa$Tco)[aux.index.choices]
                ),
                type = "scatter",
                mode = "markers",
                marker = list(size = 5, opacity = 1),
                colors = paletaintegrada,
                color = factor("Loadings"),
                symbol = factor(rep(levelchoice,variablesxnivel[factor(levelchoice,levels = datasetnames)]), levels = datasetnames),
                symbols = simbolos[1:length(datasetnames)]
              )
            
            mcoa_ScorePlot <-
              plotly::add_trace(
                mcoa_ScorePlot,
                as.data.frame(mcia_object$mcoa$SynVar),
                x = ~ mcia_object$mcoa$SynVar[, compX],
                y = ~ mcia_object$mcoa$SynVar[, compY],
                text = paste(
                  "Sample:",
                  rownames(mcia_object$mcoa$SynVar),
                  sep = " "
                ),
                showlegend = TRUE,
                type = "scatter",
                mode = "markers",
                color = factor(treatmentstable[, 1], levels = unique(
                  treatmentstable[, 1]
                )),
                colors = paletaintegrada[2:length(paletaintegrada)],
                marker = list(size = 11),
                yaxis = "y",
                xaxis = "x"
              )
            
            mcoa_ScorePlot <-
              plotly::layout(
                mcoa_ScorePlot,
                
                xaxis = list(
                  title = list(
                    text = (paste("Component", compX, sep = " ")),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                yaxis = list(
                  title = list(
                    text = paste("Component", compY, sep = " "),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                
                title = list(text = "MCIA Biplot",
                             font = list(size = fontsizes[3])),
                legend = list(font = list(size = fontsizes[4]))
              )
            return(mcoa_ScorePlot)
          }
          
          if (useannot == TRUE) {
            mapmanlevels <-
              as.numeric(unique(annotations[order(as.numeric(annotations[aux.index.choices, 3])), 3]))
            mapmannames <-
              unique(annotations[order(as.numeric(annotations[aux.index.choices, 3])), 4])
            mcoa_ScorePlot <- plotly::plot_ly()
            mcoa_ScorePlot <-
              plotly::add_trace(
                mcoa_ScorePlot,
                as.data.frame(mcia_object$mcoa$SynVar),
                x = ~ mcia_object$mcoa$SynVar[, compX],
                y = ~ mcia_object$mcoa$SynVar[, compY],
                # hoverinfo ="text",
                text = paste(
                  "Sample:",
                  rownames(mcia_object$mcoa$SynVar),
                  sep = " "
                ),
                showlegend = TRUE,
                type = "scatter",
                mode = "markers",
                color = tratamientocolores,
                colors = paleta_tratamientos[1:length(unique(tratamientocolores))],
                symbol = factor(rep(levelchoice,variablesxnivel[factor(levelchoice,levels = datasetnames)]), levels = datasetnames),
                symbols = simbolos[1:length(datasetnames)],
                marker = list(size = 11),
                yaxis = "y",
                xaxis = "x"
              )
            
            mcoa_ScorePlot <-
              plotly::add_trace(
                mcoa_ScorePlot,
                as.data.frame(mcia_object$mcoa$Tco),
                x = ~ mcia_object$mcoa$Tco[aux.index.choices, compX],
                y = ~ mcia_object$mcoa$Tco[aux.index.choices, compY],
                text = paste(
                  "ID:",
                  rownames(mcia_object$mcoa$Tco)[aux.index.choices],
                  "</br> Description: ",
                  annotations[, 2][aux.index.choices],
                  "</br> Mercator Bin: ",
                  annotations[, 4][aux.index.choices]
                ),
                type = "scatter",
                mode = "markers",
                marker = list(size = 6, opacity = 1),
                color = factor(annotations[aux.index.choices, 4], levels =
                                 mapmannames),
                colors = paleta_mapman[mapmanlevels]
              )
            
            mcoa_ScorePlot <-
              plotly::layout(
                mcoa_ScorePlot,
                xaxis = list(
                  title = list(
                    text = (paste("Component", compX, sep = " ")),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                
                yaxis = list(
                  title = list(
                    text = paste("Component", compY, sep = " "),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                
                title = list(text = "MCIA Biplot",
                             font = list(size = fontsizes[3])),
                legend = list(font = list(size = fontsizes[4]))
              )
            return(mcoa_ScorePlot)
          }
        }
      }
      
      if (treatment == 4) {
        if (levelchoice == "all") {
          if (useannot == FALSE) {
            tratamientocolores <- treatmentstable[, 1]
            paletaintegrada <-
              c("#466fc7", paleta_tratamientos[1:length(unique(treatmentstable[, 1]))])
            
            mcoa_ScorePlot <- plotly::plot_ly()
            mcoa_ScorePlot <-
              plotly::add_trace(
                mcoa_ScorePlot,
                as.data.frame(mcia_object$mcoa$Tco),
                x = ~ mcia_object$mcoa$Tco[, compX],
                y = ~ mcia_object$mcoa$Tco[, compY],
                text = paste(
                  "ID:",
                  rownames(mcia_object$mcoa$Tco)
                ),
                type = "scatter",
                mode = "markers",
                marker = list(size = 5, opacity = 1),
                color = as.factor("Loadings"),
                colors = paletaintegrada,
                symbol = factor(rep(
                  simbolos[1:length(datasetnames)], as.vector(mcia_object$mcoa$blo)
                ), levels = datasetnames),
                symbols = simbolos[(1 + length(unique(treatmentstable[, 2]))):(1 +
                                                                                 length(unique(treatmentstable[, 2])) + length(unique(treatmentstable[, 2])))]
              )
            
            mcoa_ScorePlot <-
              plotly::add_trace(
                mcoa_ScorePlot,
                as.data.frame(mcia_object$mcoa$SynVar),
                x = ~ mcia_object$mcoa$SynVar[, compX],
                y = ~ mcia_object$mcoa$SynVar[, compY],
                text = paste(
                  "Sample:",
                  rownames(mcia_object$mcoa$SynVar),
                  sep = " "
                ),
                showlegend = TRUE,
                type = "scatter",
                mode = "markers",
                color = factor(treatmentstable[, 1], levels = c(unique(
                  treatmentstable[, 1]
                ))),
                colors = paletaintegrada[2:length(paletaintegrada)],
                marker = list(size = 11),
                symbol = factor(treatmentstable[, 2], levels = unique(treatmentstable[, 2])),
                symbols = simbolos[1:length(unique(treatmentstable[, 2]))],
                yaxis = "y",
                xaxis = "x"
              )
            
            mcoa_ScorePlot <-
              plotly::layout(
                mcoa_ScorePlot,
                
                xaxis = list(
                  title = list(
                    text = paste("Component", compX, sep = " "),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                yaxis = list(
                  title = list(
                    text = paste("Component", compY, sep = " "),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                
                title = list(text = "MCIA Biplot",
                             font = list(size = fontsizes[3])),
                
                legend = list(font = list(size = fontsizes[4]))
              )
            return(mcoa_ScorePlot)
          }
          
          if (useannot == TRUE) {
            #FLAG
            mapmanlevels <-
              as.numeric(unique(annotations[order(as.numeric(annotations[, 3])), 3]))
            mapmannames <-
              annotations[order(as.numeric(annotations[, 3])),]
            mapmannames <- as.vector(unique(mapmannames[, 4]))
            paletaintegrada <-
              c(paleta_mapman[mapmanlevels], paleta_tratamientos[1:length(unique(treatmentstable[, 1]))])
            
            mcoa_ScorePlot <- plotly::plot_ly()
            mcoa_ScorePlot <-
              plotly::add_trace(
                mcoa_ScorePlot,
                as.data.frame(mcia_object$mcoa$Tco),
                x = ~ mcia_object$mcoa$Tco[, compX],
                y = ~ mcia_object$mcoa$Tco[, compY],
                text = paste(
                  "ID:",
                  rownames(mcia_object$mcoa$Tco),
                  "</br> Description: ",
                  annotations[, 2],
                  "</br> Mercator Bin: ",
                  annotations[, 4]
                ),
                type = "scatter",
                mode = "markers",
                marker = list(size = 5, opacity = 1),
                color = as.factor("Loadings"),
                colors = paletaintegrada,
                symbol = factor(rep(
                  simbolos[1:length(datasetnames)], as.vector(mcia_object$mcoa$blo)
                ), levels = datasetnames),
                symbols = simbolos[1:length(datasetnames)]
              )
            
            mcoa_ScorePlot <-
              plotly::add_trace(
                mcoa_ScorePlot,
                as.data.frame(mcia_object$mcoa$SynVar),
                x = ~ mcia_object$mcoa$SynVar[, compX],
                y = ~ mcia_object$mcoa$SynVar[, compY],
                text = paste(
                  "Sample:",
                  rownames(mcia_object$mcoa$SynVar),
                  sep = " "
                ),
                showlegend = TRUE,
                type = "scatter",
                mode = "markers",
                color = factor(treatmentstable[, 1], levels = c(unique(
                  treatmentstable[, 1]
                ))),
                colors = paletaintegrada[2:length(paletaintegrada)],
                marker = list(size = 11),
                symbol = factor(treatmentstable[, 2], levels = unique(treatmentstable[, 2])),
                symbols = simbolos[1:length(unique(treatmentstable[, 2]))],
                yaxis = "y",
                xaxis = "x"
              )
            
            mcoa_ScorePlot <-
              plotly::layout(
                mcoa_ScorePlot,
                xaxis = list(
                  title = list(
                    text = (paste("Component", compX, sep = " ")),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                
                yaxis = list(
                  title = list(
                    text = (paste("Component", compY, sep = " ")),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                
                title = list(text = "MCIA Biplot",
                             font = list(size = fontsizes[3])),
                legend = list(font = list(size = fontsizes[4]))
              )
            return(mcoa_ScorePlot)
          }
        }
        
        
        if (levelchoice != "all") {
          if (levelchoice %in% datasetnames == FALSE)
            stop("Plot Var error: Please select a valid datasetname")
          
          aux.index.all <- factor(rep(
            names(mcia_object$mcoa$blo), variablesxnivel), levels = datasetnames) 
          aux.index.choices <- which(aux.index.all %in% levelchoice)
          
          if (useannot == FALSE) {
            mcoa_ScorePlot <- plotly::plot_ly()
            mcoa_ScorePlot <-
              plotly::add_trace(
                mcoa_ScorePlot,
                as.data.frame(mcia_object$mcoa$SynVar),
                x = ~ mcia_object$mcoa$SynVar[, compX],
                y = ~ mcia_object$mcoa$SynVar[, compY],
                # hoverinfo ="text",
                text = paste(
                  "Sample:",
                  rownames(mcia_object$mcoa$SynVar),
                  sep = " "
                ),
                showlegend = TRUE,
                type = "scatter",
                mode = "markers",
                color = factor(treatmentstable[, 1], levels = unique(treatmentstable[, 1])),
                colors = paleta_tratamientos[1:length(unique(treatmentstable[, 1]))],
                symbol = factor(treatmentstable[, 2], levels = unique(treatmentstable[, 2])),
                symbols = simbolos[1:length(unique(treatmentstable[, 2]))],
                marker = list(size = 11),
                yaxis = "y",
                xaxis = "x"
              )
            
            mcoa_ScorePlot <-
              plotly::add_trace(
                mcoa_ScorePlot,
                as.data.frame(mcia_object$mcoa$Tco),
                x = ~ mcia_object$mcoa$Tco[aux.index.choices, compX],
                y = ~ mcia_object$mcoa$Tco[aux.index.choices, compY],
                text = paste(
                  "ID:",
                  rownames(mcia_object$mcoa$Tco)[aux.index.choices],
                  "</br> Description: ",
                  annotations[, 2][aux.index.choices],
                  "</br> Mercator Bin: ",
                  annotations[, 4][aux.index.choices]
                ),
                type = "scatter",
                mode = "markers",
                marker = list(size = 5, opacity = 1),
                color = factor(rep(
                  1:length(datasetnames), variablesxnivel
                ), levels = datasetnames),
                colors = paleta_niveles[1:length(datasetnames)]
              )
            mcoa_ScorePlot <-
              plotly::layout(
                mcoa_ScorePlot,
                xaxis = list(
                  title = list(
                    text = paste("Component", compX, sep = " "),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                yaxis = list(
                  title = list(
                    text = (paste("Component", compY, sep = " ")),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                
                title = list(text = "MCIA Biplot",
                             font = list(size = fontsizes[3])),
                legend = list(font = list(size = fontsizes[4]))
              )
            return(mcoa_ScorePlot)
          }
          if (useannot == TRUE) {
            #FALG
            mapmanlevels <-
              as.numeric(unique(annotations[order(as.numeric(annotations[aux.index.choices, 3])), 3]))
            mapmannames <-
              unique(annotations[order(as.numeric(annotations[aux.index.choices, 3])), 4])
            
            mcoa_ScorePlot <- plotly::plot_ly()
            mcoa_ScorePlot <-
              plotly::add_trace(
                mcoa_ScorePlot,
                as.data.frame(mcia_object$mcoa$SynVar),
                x = ~ mcia_object$mcoa$SynVar[, compX],
                y = ~ mcia_object$mcoa$SynVar[, compY],
                # hoverinfo ="text",
                text = paste(
                  "Sample:",
                  rownames(mcia_object$mcoa$SynVar),
                  sep = " "
                ),
                showlegend = TRUE,
                type = "scatter",
                mode = "markers",
                color = factor(treatmentstable[, 1], levels = unique(treatmentstable[, 1])),
                colors = paleta_tratamientos[1:length(unique(treatmentstable[, 1]))],
                symbol = factor(treatmentstable[, 2], levels = unique(treatmentstable[, 2])),
                symbols = simbolos[1:length(unique(treatmentstable[, 2]))],
                marker = list(size = 11),
                yaxis = "y",
                xaxis = "x"
              )
            mcoa_ScorePlot <-
              plotly::add_trace(
                mcoa_ScorePlot,
                as.data.frame(mcia_object$mcoa$Tco),
                x = ~ mcia_object$mcoa$Tco[aux.index.choices, compX],
                y = ~ mcia_object$mcoa$Tco[aux.index.choices, compY],
                text = paste(
                  "ID:",
                  rownames(mcia_object$mcoa$Tco)[aux.index.choices],
                  "</br> Description: ",
                  annotations[, 2][aux.index.choices],
                  "</br> Mercator Bin: ",
                  annotations[, 4][aux.index.choices]
                ),
                type = "scatter",
                mode = "markers",
                marker = list(size = 6, opacity = 1),
                color = factor(annotations[aux.index.choices, 4], levels =
                                 mapmannames),
                colors = paleta_mapman[mapmanlevels]
              )
            mcoa_ScorePlot <-
              plotly::layout(
                mcoa_ScorePlot,
                
                xaxis = list(
                  title = list(
                    text = (paste("Component", compX, sep = " ")),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                
                yaxis = list(
                  title = list(
                    text = (paste("Component", compY, sep = " ")),
                    font = list(size = fontsizes[1])
                  ),
                  tickfont = list(size = fontsizes[2])
                ),
                
                title = list(text = "MCIA Biplot",
                             font = list(size = fontsizes[3])),
                legend = list(font = list(size = fontsizes[4]))
              )
            return(mcoa_ScorePlot)
          }
        }
      }
    }
    # Pseudoeigen plot ----
    if (plottype == "Pseudoeigen") {
      if(levelchoice == "all") levelchoice <- names(mcia_list$mcia$mcoa$blo)
      # this plot depicts how close are the different dataset levels taking into account their eigenvalues
      mcoa_ScorePlot <-
        plotly::plot_ly(
          as.data.frame(mcia_object$mcoa$cov2),
          x = ~ mcia_object$mcoa$cov2[, compX],
          y = ~ mcia_object$mcoa$cov2[, compY],
          type = "scatter",
          mode = "markers",
          marker = list(size = 11, opacity = 1),
          color = factor(levelchoice, levels =
                           unique(datasetnames)),
          colors = paleta_niveles[1:length(datasetnames)],
          hoverinfo = "none"
        )
      
      mcoa_ScorePlot <-
        plotly::layout(
          mcoa_ScorePlot,
          title = list(text = "Pseudoeigenvalues. All datasets",
                       font = list(size = fontsizes[3])),
          
          xaxis = list(
            title = list(
              text = paste("Pseudoeigenvalue", compX, sep = " "),
              font = list(size = fontsizes[1])
            ),
            tickfont = list(size = fontsizes[2])
          ),
          
          yaxis = list(
            title = list(
              text = (paste("Pseudoeigenvalue", compY, sep = " ")),
              font = list(size = fontsizes[1])
            ),
            tickfont = list(size = fontsizes[2])
          ),
          
          legend = list(font = list(size = fontsizes[4]))
        )
      return(mcoa_ScorePlot)
    }
    # Composite plot ----
    if (plottype == "Composite") {
      if (!is.null(compZ))
        stop("Composite plot can only draw 2D plots. compZ must be null")
      #Representamos los eigenvalues, y luego como sube la proporcion acumulada.
      
      p1 <-
        mcia_plot(mcia_list=mcia_list, treatment=treatment, compX=compX, compY=compY, plottype = "SynVar")
     
     
      p2 <-
        mcia_plot(
          mcia_list=mcia_list,
          treatment=treatment,
          compX=compX,
          compY=compY,
          plottype = "Var",
          useannot = FALSE,
          levelchoice = "all"
        )
    
      p3 <-
        mcia_plot(mcia_list=mcia_list, treatment=treatment, compX=compX, compY=compY, plottype = "CoIn")
     
      p4 <-
        mcia_plot(mcia_list=mcia_list, treatment=treatment, compX=compX, compY=compY, plottype = "Pseudoeigen")
      mcoa_ScorePlot <-
        plotly::subplot(
          subplot(p1, p2),
          subplot(p3, p4),
          nrows = 2,
          shareX = F,
          shareY = F,
          margin = 0.04
        )
    
       mcoa_ScorePlot <-
        plotly::layout(mcoa_ScorePlot, title = "MCOA Analysis")
       mcoa_ScorePlot
      return(mcoa_ScorePlot)
    }
    # All ----
    if (plottype == "All") {
      #recursive call
      if (!is.null(compZ))
        stop("Please select only two dimensions for plotting all figures")
      cat("EXPORTING ANALYSIS PLOTS\nA single core will be used. It may take a while...\n ")
      cat("Generating and saving SynVar plot. Step 1/6\n")
      export_plot(
        mcia_plot(
          mcia_list,
          treatment = treatment,
          compX = compX,
          compY = compY,
          plottype = "SynVar",
          useannot = useannot,
          levelchoice = levelchoice
        ),
        "mcoa_synvar.pdf"
      )
      cat("Generating and saving Scree plot. Step 2/6\n")
      export_plot(
        mcia_plot(
          mcia_list,
          treatment = treatment,
          compX = compX,
          compY = compY,
          plottype = "Scree",
          useannot = useannot,
          levelchoice = levelchoice
        ),
        "mcoa_scree.pdf"
      )
      cat("Generating and saving Var plot. Step 3/6\n")
      export_plot(
        mcia_plot(
          mcia_list,
          treatment = treatment,
          compX = compX,
          compY = compY,
          plottype = "Var",
          useannot = useannot,
          levelchoice = levelchoice
        ),
        "mcoa_var.pdf"
      )
      cat("Generating and saving CoInertia plot. Step 4/6\n")
      export_plot(
        mcia_plot(
          mcia_list,
          treatment = treatment,
          compX = compX,
          compY = compY,
          plottype = "CoIn",
          useannot = useannot,
          levelchoice = levelchoice
        ),
        "mcoa_coin.pdf"
      )
      cat("Generating and saving Var plot. Step 5/6\n")
      export_plot(
        mcia_plot(
          mcia_list,
          treatment = treatment,
          compX = compX,
          compY = compY,
          plottype = "Pseudoeigen",
          useannot = useannot,
          levelchoice = levelchoice
        ),
        "mcoa_pseudoeigen.pdf"
      )
      cat("Generating and saving Composite plot. Step 6/6\n")
      export_plot( 
        mcia_plot(
          mcia_list,
          treatment = treatment,
          compX = compX,
          compY = compY,
          plottype = "Composite",
          useannot = useannot,
          levelchoice = levelchoice
        ),
        "mcoa_composite.pdf"
      )
    }
  }
